agency/urls.py
from django.urls import path

from agency.views import index, TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView, NewspaperListView, \
    NewspaperDetailView, NewspaperCreateView, NewspaperUpdateView, NewspaperDeleteView, RedactorListView, \
    RedactorDetailView, RedactorCreateView, RedactorDeleteView, RedactorUpdateView, MyPageView

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list",),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create",),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update",),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete",),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(), name="redactor-delete"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("agency/about/", MyPageView.as_view(), name='about'),
]

app_name = "newspaper"

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("", include('admin_material.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("agency:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from agency.models import Redactor, Newspaper


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    model = forms.CharField(max_length=255, required=False)


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + ("years_of_experience", "first_name", "last_name")


class RedactorSearchForm(forms.Form):
    username = forms.CharField(max_length=255, required=False)


class TopicSearchForm(forms.Form):
    name = forms.CharField(max_length=255, required=False)

agency/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from .forms import RedactorCreationForm, NewspaperForm
from .models import Redactor, Newspaper, Topic


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "agency/topic_list.html"
    paginate_by = 20


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 20
    queryset = Newspaper.objects.all().select_related("topic")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 20


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    fields = "__all__"
    success_url = reverse_lazy("agency:redactor-list")
    template_name = "agency/redactor_confirm_delete.html"


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    fields = ("username", "years_of_experience", "first_name", "last_name", "email")
    success_url = reverse_lazy("agency:redactor-list")


@login_required
def redactor_assign(request, pk):
    newspaper = Newspaper.objects.get(pk=pk)
    redactor = Redactor.objects.get(pk=request.user.pk)
    if redactor in newspaper.redactors.all():
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("agency:newspaper-detail", args=[pk]))


class MyPageView(TemplateView):
    template_name = "agency/about.html"


templates/accounts/login.html
{% extends 'layouts/base-fullscreen.html' %}
{% load i18n static admin_material %}

{% block content %}

  {% include 'includes/navigation-fullscreen.html' %}

  <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                    Sign IN
                  </h4>
                  <div class="row mt-3">
                    <p class="mb-0 text-white text-center">
                      {% if msg %}
                        {{ msg | safe }}
                      {% else %}
                        Add your credentials
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
              <div class="card-body">

                <form method="post" role="form" class="text-start" action="#">

                  {% csrf_token %}
                  {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                      <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                  {% endif %}

                  {% for field in form %}
                  <div class="input-group input-group-outline mb-3">
                    {{ field }}
                  </div>
                  {% endfor %}
              
                  
                  <p class="mt-3 text-sm">
                    <a href="{% url 'password_reset' %}" class="text-primary text-gradient font-weight-bold">Forgot Password?</a>
                  </p>

                  <div class="text-center">
                    <button type="submit" class="btn bg-gradient-primary w-100 my-0 mb-2">Sign in</button>
                  </div>

                  <p class="mt-4 text-sm text-center">
                    Don't have an account?
                    <a href="#" class="text-primary text-gradient font-weight-bold">Sign UP</a>
<!--                    <a href="{% url 'register' %}" class="text-primary text-gradient font-weight-bold">Sign UP</a>-->
                  </p>

                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
        {% include 'includes/footer-fullscreen.html' %}
    </div>
  </main>


{% endblock content %}

templates/agency/about.html

{% extends "base.html" %}
{% load i18n static %}

{% block title %} Tables {% endblock title %}

{% block content %}

    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">About</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <div class="ppp">
                  Dear visitors,
                  <br><br>
                  I am excited to introduce you to this invented web service, which is my pet project aimed at enhancing my backend web development skills using Python and Django.<br>
                  The database is based on three interconnected models: Newspapers, Topics, and Redactors.
                  Each topic can have several newspapers, each newspaper can have several redactors, and each redactor can work on several newspapers.
                  On this website, you can create, modify, and delete any of these data using web-interface.
                  <br><br>
                  In addition, there are implemented user authentication with secure creation of new users.
                  Passwords in the database are stored in a hashed form, ensuring the safety of our users' personal information.
                  <br><br>
                  Thank you for your attention.
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}
 

templates/agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.model }}
  </h1>

  <div class="container-fluid py-4">
    <div class="row ppp">
      <div class="col-12">
        <div class="card my-4">
          <div class="card-body px-0 pb-2">
            <div class="ppp">

              <h4>Topic: {{ newspaper.topic.name }}</h4>
              <h5>Title: {{ newspaper.title }}</h5>
              <ul>
              {% for redactor in newspaper.publishers.all %}
                <li>Redactors: {{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }})</li>
              {% endfor %}
              </ul>
                <p>{{ newspaper.content }}</p>

            </div>
          </div>
        </div>
      </div>
    </div>


      <a href="{% url 'agency:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger ">
      Delete
    </a>
    <a href="{% url 'agency:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary ">
      Update
    </a>
{% endblock %}

templates/agency/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="card my-4">
        <div class="container">
          <div class="card-body">
            <div class="col-12">
              <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
              <form action="" method="post" novalidate class="bg-gradient">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/agency/newspaper_list.html
{% extends "base.html" %}
{% load i18n static %}
{% block title %} Tables {% endblock title %}

{% block content %}
  <h1>
    Newspaper list
    <a href="{% url 'agency:newspaper-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if newspaper_list %}

    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">

            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Authors table</h6>
              </div>
            </div>

            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <tr>
                    <th>ID</th>
                    <th>Topic</th>
                    <th>Title</th>
                    <th>Published_date</th>
                    <th>Update / Delete</th>
                  </tr>
                    {% for newspaper in newspaper_list %}
                      <tr>
                        <td>{{ newspaper.id }}</td>
                        <td>{{ newspaper.topic.name }}</td>
                        <td><a href="{% url "agency:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.title }} </a></td>
            {#            <td>{{ newspaper.publishers }}</td>#}
                        <td>{{ newspaper.published_date }}</td>
                        <td><a class="btn btn-outline-secondary" href="{% url "agency:newspaper-detail" pk=newspaper.id %} ">Detail</a></td>
                      </tr>
                    {% endfor %}

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  {% else %}
    <p>There are no newspapers in agency</p>
  {% endif %}
{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="button" onclick="location.href='{% url 'agency:redactor-list' %}'">Cancel</button>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="ppp">
    <h1>
      Username: {{ redactor.username }}
    </h1>

    <p><strong>First name:</strong> {{ redactor.first_name }}</p>
    <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
    <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
    <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

    <div class="ml-3">
      <h4>Newspapers</h4>

      {% for newspaper in redactor.newspapers.all %}
          <hr>
          <p><strong>Title:</strong> {{ newspaper.title }}</p>
          <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
          <p class="text-muted"><strong>Id:</strong> {{newspaper.id}}</p>

      {% empty %}
        <p>No newspapers!</p>
      {% endfor %}
    </div>
      <button class="btn btn-success" type="button" onclick="location.href='{% url 'agency:redactor-update' pk=redactor.pk %}'">Update</button>
      <button class="btn btn-danger" type="button" onclick="location.href='{% url 'agency:redactor-delete' pk=redactor.pk %}'">Delete</button>
  </div>
{% endblock %}

templates/agency/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="container-lg py-4">
    <div class="row">
      <div class="card my-4">
        <div class="container-lg">
          <div class="card-body">
            <div class="col-12">
              <h4>{{ object|yesno:"Update,Create" }} redactor</h4>
              <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}
{% load i18n static %}
{% block title %} Tables {% endblock title %}

{% block content %}
    <h1>Redactor List
      <a href="{% url 'agency:redactor-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

  {% if redactor_list %}

    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">

            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Redactors table</h6>
              </div>
            </div>

            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">

                  <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Years of experience</th>
                    <th>Update / Delete</th>
                  </tr>

                {% for redactor in redactor_list %}
                  <tr>
                    <td>{{ redactor.id }}</td>
                    <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
                    <td>{{ redactor.first_name }}</td>
                    <td>{{ redactor.last_name }}</td>
                    <td>{{ redactor.years_of_experience }}</td>
                    <td><a class="btn btn-outline-secondary" href="{{ redactor.get_absolute_url }}"> Detail </a></td>
                  </tr>

                {% endfor %}

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    {% else %}
      <p>There are no redactors in the service.</p>
    {% endif %}

{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/agency/topic_form.html
{% extends "base.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}


  <div class="container">
    <div class="card-body">
      <h4>{{ object|yesno:"Update,Create" }} topic</h4>
      <div class="input-group input-group-outline my-3">
        <form action="" method="post" novalidate >
          {% csrf_token %}
          {{ form.as_p }}
          <br>
          <input type="submit" value="Submit" class="btn btn-secondary">
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/agency/topic_list.html
{% extends "base.html" %}

{% block content %}
  <div class="ppp">
    <h1>
      Topic List
      <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    {% if topic_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>

          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for topic in topic_list %}
          <tr>
            <td>
                {{ topic.id }}
            </td>
            <td>
                {{ topic.name }}
            </td>

            <td>
                <a href="{% url 'agency:topic-update' pk=topic.id %}">
                  Update
                </a>
              </td>
              <td>
                <a style="color: red"
                  href="{% url 'agency:topic-delete' pk=topic.id %}">
                  Delete
                </a>
              </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no topics in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/includes/_footer.html
<footer class="footer py-4  ">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6 mb-lg-0 mb-4">
        <div class="copyright text-center text-sm text-muted text-lg-start">
          &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
          Coded by AppSeed.
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://appseed.us/product/material-dashboard/django/" class="nav-link text-muted" target="_blank">Download</a>
          </li>
          <li class="nav-item">
            <a href="https://appseed.us/product/material-dashboard2-pro/django/" class="nav-link text-muted" target="_blank">PRO Version</a>
          </li>
          <li class="nav-item">
            <a href="https://appseed.us/support/" class="nav-link text-muted" target="_blank">Support</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer-fullscreen.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          Django pet project by
          &copy; <a href="https://github.com/inrock1" class="text-white font-weight-bold" target="_blank">Kaskov Yevhen</a>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">

          <li class="nav-item">
            <a href="{% url 'agency:about' %}" class="nav-link text-white" target="_blank">About</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-fullscreen.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid ps-2 pe-0">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'agency:index' %}">Newspapers agency</a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse" id="navigation">
              <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                  <a class="nav-link me-2" href="{% url 'login' %}">
                    <i class="fas fa-key opacity-6 text-dark me-1"></i>
                    Sign In
                  </a>
                </li>
              </ul>

            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/sidebar.html
{% load i18n static %}

  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="{% url 'agency:index' %}" target="_blank">
        <img src="{% static 'img/logo-ct.png' %}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">Newspaper agency</span>
      </a>
    </div>

    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">


        <li class="nav-item">
          <a class="nav-link text-white {% if 'tables' in segment %} active {% endif %} " href="{% url 'agency:newspaper-list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">table_view</i>
            </div>
            <span class="nav-link-text ms-1">Newspapers</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white {% if 'billing' in segment %} active {% endif %} " href="{% url 'agency:topic-list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">receipt_long</i>
            </div>
            <span class="nav-link-text ms-1">Topics</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white {% if 'vr' in segment %} active {% endif %} " href="{% url 'agency:redactor-list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">view_in_ar</i>
            </div>
            <span class="nav-link-text ms-1">Redactors</span>
          </a>
        </li>

        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'logout'%}?next={{request.path}}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">login</i>
            </div>
            <span class="nav-link-text ms-1">Logout</span>
          </a>
        </li>

              <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'agency:about' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">assignment</i>
            </div>
            <span class="nav-link-text ms-1">About</span>
          </a>
        </li>

      </ul>
    </div>

  </aside>